### ISSUE TITLE
💭 Support other HTML templating languages (eg. smarty .tpl)

### ISSUE THREAD

**Issue by thebspin** [rome/tools#1016]
I wonder if there is a possibility to easily support .tpl files (and others maybe aswell framework depending like twig and blade).
From what i understand right now rome sees them als text files and just ignores them.
But in fact they are just html files with with some extra syntaxing depending on the framework.

For example in smarty i could have this:

```
{if $user.id != 0 && true}
    <div id="pushnot" class="display-hidden margin-bottom-20" style="margin-top: -20px">
        <ins data-a-zid="1" data-a-id="ff1268146c6b47ab4f398196826cf055e7ed1d7e"></ins>
    </div>
{/if}
```

This is just valid html with around them smarty syntax.
By just ignoring the smarty templating that always starts with { the rest of the file could still be parsed and would be formatted and linted properly.

I'd love to hear what others think about this.

**Comment by sebmck** [comment]
There _might_ be a place for us to support this, depending on maintenance overhead and complexity. I can see us adding `.tpl` as being parsable as HTML, and it would just be automatically linted and work everywhere. My concern would be adding magic to detect the `{}` since otherwise we will parse it as regular text and when formatting will just print it as:

```
{if $user.id != 0 && true}
<div id="pushnot" class="display-hidden margin-bottom-20" style="margin-top: -20px">
  <ins data-a-zid="1" data-a-id="ff1268146c6b47ab4f398196826cf055e7ed1d7e"></ins>
</div>
{/if}
```

Which looks a bit nasty. This could potentially be somewhere plugins fit in. I can imagine us having a very basic way to extend HTML support with custom operators for different template languages. Depends on what strategy we settle on. It would be nice to have it in core if it was very simple and would have significant usage.

**Comment by sebmck** [comment]
I renamed the issue to generally track supporting other "HTML" templating languages. I don't imagine we'll get to this soon unless someone is sufficiently motivated to work on this (I can provide some guidance and support). Thank you for the suggestion!

**Comment by thebspin** [comment]
> I renamed the issue to generally track supporting other "HTML" templating languages. I don't imagine we'll get to this soon unless someone is sufficiently motivated to work on this (I can provide some guidance and support). Thank you for the suggestion!

If you could point me in the right direction i would not mind giving it a go.

**Comment by sebmck** [comment]
@thebspin Our HTML parser (located in `internal/html-parser`) is pretty bad. I wrote it off the cuff just so we had something, and it's not standards compliant at all. Improving the parser, and then enabling HTML support would be a prerequisite for this task. HTML linting/formatting support is currently disabled. You can enable it by setting the `capabilities` to `true` in `internal/core/common/file-handlers/html.ts` and then running `rome check foo.html` to test.
