### ISSUE TITLE
🐛 Windows 10 line endings errors on `check`

### ISSUE THREAD

**Issue by estevanmaito** [rome/tools#1065]
The entire error result:

https://gist.github.com/estevanmaito/b0686f12b4b988dc73b4a53822765510

## Previous conversation on Discord

**Sebastian Today at 4:21 PM**
yeah it's line endings
can you open an issue?
when we format code, if the original file contained \r then we use \r\n newlines instead of \n

**ematipicoToday at 4:22 PM**
Maybe we'd need some more settings inside .gitattributes

**Sebastian Today at 4:22 PM**
there's no other reliable way to detect what the correct line endings should be
oh nice, didn't know you could specify correct line endings there

**ematipico Today at 4:23 PM**
I mean that's how we fixed issues around line endings

**Sebastian Today at 4:23 PM**
oh wait i know what's going on
actually i have no idea lol
there's a double carriage return though on line 3 which is weird

## Environment

```
$ rome rage --summary
Environment Variables
  Object {}

User Config
  unset

Rome Version
  10.0.4-beta-dev

Node Version
  14.2.0

Platform
  win32 x64 10.0.18362

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 120
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: false
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "<REDACTED>"
    realCwd: "<REDACTED>"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_435_584
      pid: 8_012
      uptime: 0.2022569
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_435_584
        ownedBytes: 0
        ownedFileCount: 0
        pid: 8_012
        uptime: 0.2021891
      }
    ]
  }
```

## Steps To Reproduce

1. Clone the project
2. Run `./rome check`

**Comment by sebmck** [comment]
The thing that stands out to me here, is that all the modified lines specifically have `\r\r` which is really weird. You'll notice that we print invisible characters when display code, primarily to identify bugs and changes like this. `\r` is printed as `␍` for example, which is the unicode presentation character for a carriage return.

It's also odd that we're printing the trailing `\r` in the first place. We should ideally hide it since Windows users will almost always have line endings this way and it looks awful. That isn't a bug though, just not something that has been implemented. I wonder if we could get away with just using `process.platform === "win32"` and not display a single `\r` when at the end of a line, or if that's too naive.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
