### ISSUE TITLE
💭 Support for module alias / module resolution

### ISSUE THREAD

**Issue by adeyahya** [rome/tools#1137]
I'm using module alias in typescript

tsconfig.json
```json
{
  "compilerOptions": {
    "paths": {
      "@lib": ["lib/index.ts"],
      "@lib/*": ["lib/*"]
    }
  }
}
``` 

but the linter saying `Cannot find @lib`
@sebmck answering [my question](https://discordapp.com/channels/678763474494423051/714237988145594428/746109838051901501) on discord, saying that this options doesn't available yet

I think it would be nice if the config same as typescript and Rome able to infer if not specified
```json
{
  "paths": {
      "@lib": ["lib/index.ts"],
      "@lib/*": ["lib/*"]
    }
}
```

**Comment by sebmck** [comment]
This isn't actually specific to the linter and if we add support for this, will automatically work with the bundler too!

With #1112 we can even automatically populate the Rome config with rules inferred from `tsconfig.json` (Just wanted to note that I am vehemently against us automatically doing this during project load. I think this should be an explicit action since we shouldn't be relying on other peoples APIs and configuration for such a critical path)

**Comment by ematipico** [comment]
Closing this in favour of #1555
