### ISSUE TITLE
📎 File handler for *.txt

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1315]
Implement a file handler for *.txt files

**Comment by sebmck** [comment]
What's the intended functionality?

**Comment by jer3m01** [comment]
> What's the intended functionality?

For the moment rome crashes when it encounters a txt file, just something to ignore the file (similar way than fonts).

Don't think we can do much more than ignore the file (ie an empty file handler).

**Comment by sebmck** [comment]
Oh what does the crash look like? I think we throw a pretty poor error when we resolve to a file that's missing a file handler. We can also improve that as a separate task.

**Comment by jer3m01** [comment]
![image](https://user-images.githubusercontent.com/33844379/106920683-a1b18900-670b-11eb-8e87-3c482d136ad8.png)

**Comment by sebmck** [comment]
Just opened #1334 which I think addresses this in the best way. When you run a command like `rome check foo.txt` or import a file we don't have a handler for you'll get the following diagnostic:

<img width="621" alt="Screen Shot 2021-02-04 at 11 51 09 PM" src="https://user-images.githubusercontent.com/853712/106996650-f7575700-6746-11eb-8d70-dce45ada7b29.png">

I also think we should probably remove a bunch of the asset extensions we have hardcoded anyway since you could also specify them in your config.
