### ISSUE TITLE
🐛 Markup not applying correctly

### ISSUE THREAD

**Issue by jer3m01** [rome/tools#1367]
## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    LANG: "C.UTF-8"
    TERM: "xterm-256color"
  }

User Config
  unset

Rome Version
  10.0.5-beta-dev

Node Version
  12.18.3

Platform
  linux x64 4.4.0-19041-Microsoft

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 8
    columns: 472
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    silent: false
    cwd: AbsoluteFilePath</mnt/d/Webstorm/jer3m01/rome>
    realCwd: AbsoluteFilePath</mnt/d/Webstorm/jer3m01/rome>
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 29_294_592
      pid: 1_306
      uptime: 0.9347237
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 29_294_592
        ownedBytes: 0n
        ownedFileCount: 0
        pid: 1_306
        uptime: 0.9345913
      }
    ]
  }

```

## Steps To Reproduce

1. In `scripts/`
```ts
import {reporter} from "./_utils";
import {markup} from "@internal/markup";

reporter.log(markup`
<approx>2.99999</approx>
`);
```
2. `rome run scripts/{file}`
![image](https://user-images.githubusercontent.com/33844379/107867086-d34af280-6e77-11eb-8487-51672b3cffae.png)

## Expected Results
Correctly parse `<emphasis></emphasis>`

**Comment by sebmck** [comment]
That error is correct, I think you want "duration"

**Comment by jer3m01** [comment]
> 
> 
> That error is correct, that's not a valid tag name. I think you want "duration".

I meant the 
![image](https://user-images.githubusercontent.com/33844379/107867138-697f1880-6e78-11eb-8bda-9cc84d5cbb36.png)

**Comment by sebmck** [comment]
Ah! This is actually intentional, although it is confusing.

The `DiagnosticError` here is being propagated to the `rome run` command handler. However we do not detect this `DiagnosticError` instance to be one we can display as it's constructor is different as it's from the compiled script, and not the binary itself, so it's displayed as a regular error.

`createSingleDiagnosticError` is the constructor that's used when we want to create a `DiagnosticsError` with a single diagnostic. This helper also sets the error `name` to the raw diagnostic description markup. We perform **no** normalization and converting the markup to plain text here as the message is never intended to be displayed properly to a user, and doing so would be more expensive.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
