### ISSUE TITLE
🐛  CSS parser falls into infinity loop when parsing ratio value in media condition

### ISSUE THREAD

**Issue by yeonjuan** [rome/tools#1481]
CSS parser falls into infinity loop when parsing [ratio value](https://www.w3.org/TR/css-values-4/#ratio-value) in media condition

## Environment

```
$ rome rage --summary
Environment Variables
  {COLORTERM: "truecolor", LANG: "ko_KR.UTF-8", TERM: "xterm-256color", TERM_PROGRAM: "vscode"}

User Config
  unset

Rome Version
  10.0.7-beta.18

Node Version
  14.16.0

Platform
  darwin x64 18.7.0

Terminal Features
  {
    background: "unknown"
    colorDepth: 24
    cursor: true
    hyperlinks: true
    isTTY: true
    progress: true
    unicode: true
    columns: OneIndexedNumber<184>
  }

Client Flags
  {
    clientName: "cli"
    silent: false
      // ...
  }

Server Status
  {
    projects: [{id: 0}, {id: 1}]
    workers: [{astCacheSize: 0, heapTotal: 45_334_528, ownedBytes: 0n, ownedFileCount: 0, pid: 13_456, uptime: 1.348131835}]
    server: {heapTotal: 45_334_528, pid: 13_456, uptime: 1.348270321}
  }
```

## Steps To Reproduce

1. test.css

```css
@media (aspect-ratio: 11/5) {
}
```

2. run `./rome parse test.css`

It falls into an infinity loop. 

## Expected Results

Parsing success.

**Comment by ematipico** [comment]
Our parser doesn't support `<ratio>` at all.

This is the definition of our current `<mf-value>`, which, from the spec should be:

```
<mf-value> = <number> | <dimension> | <ident> | <ratio>
```

Our code base:

```ts
export interface CSSMediaFeatureValue extends NodeBaseWithComments {
	readonly type: "CSSMediaFeatureValue";
	readonly value: CSSNumber | CSSDimension | CSSIdentifier;
}
```

We don't have `CSSRatio` because our parser doesn't support it. It seems `<ratio>` belongs to v4 of values. Not sure how to fix the issue:
1. create a token called `"Ratio"`
2. handle this case inside the media query itself

I'm leaning towards the first solution, having a token called `"Ratio"`. Probably we will need to use `<ratio>` somewhere else in the future.
