### ISSUE TITLE
📎 `rome init` should add the Visual Studio Code extension to the workspace's recommended extensions

### ISSUE THREAD

**Issue by jonahsnider** [rome/tools#1643]
### Description

Visual Studio Code has support for [workspace recommended settings](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions). When someone opens the workspace they will be prompted to install the recommended extensions.

Rome could automatically create a `.vscode/extensions.json` file in the `rome init` command. This could help users get started using Rome for the first time, before they've installed any editor integrations.

```json
{
	"recommendations": ["rome.rome"]
}
```

![extension sidebar](https://user-images.githubusercontent.com/7608555/125708566-3a38f286-ccd1-4731-9f16-b2f2dbd717f7.png)

![notification displayed](https://user-images.githubusercontent.com/7608555/125708653-7f8ff3f0-3d34-458c-8692-69f77152c728.png)

**Comment by jamiebuilds** [comment]
Maybe. I would want to avoid annoying users with this unnecessarily, particularly people not using vscode. There may be a few things we can do to mitigate that though:

- Check if the users editor is vscode
- If they do: Prompt them to install the vscode extension themselves
- If they install the extension: Prompt them if they want to create a `extensions.json` file (probably better done by the extension than `rome init`)

**Comment by ematipico** [comment]
> If they install the extension: Prompt them if they want to create a extensions.json file (probably better done by the extension than rome init)

I don't understand this part. `extensions.json` is meant  to install recommended extensions. If a user installs the extension, then `extensions.json` loses its value. That's what I understood.

Wouldn't be better to ask the user if they use VSCode during `rome init`? The default choice would be no. They have to opt-in.

**Comment by jonahsnider** [comment]
There's some value in doing it for other users, not just the person who ran `rome init` (ex. someone outside of your organization is contributing to your project, they have no idea what Rome is until the extension is suggested to them)

**Comment by GabenGar** [comment]
> `extensions.json` is meant to install recommended extensions.

Actually it doesn't. It's merely a list of recommended extensions, which the user is free to ignore. It's pretty surprising VSCode is quite strict in this regard, being a microsoft product, and doesn't just randomly install extensions on a whim.
Also `.vscode` folder is a bit too "personal" for random third-party packages to barge in. The better approach is checking `.vscode` folder into source control and treat the configs in it as hard truth for VSCode users of the repo (since the values in this folder have the highest priority for resolution). So it's not the `rome`'s domain issue.
The discoverability of the extension is more of a SEO issue, since when I searched for `javascript linter`/`javascript formatter` in the extension tab, Rome extension was pretty low in the ranking (3rd page at least).
