### ISSUE TITLE
Move internal python script to Rust

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1930]
### Discussed in https://github.com/rome/tools/discussions/1926

<div type='discussions-op-text'>

<sup>Originally posted by **ematipico** January 11, 2022</sup>
Hi @rome/staff 

[This recent PR](https://github.com/rome/tools/pull/1910) showed us that we inherited some internal script that requires `python`.

This, as a consequence, requires for core contributors and staff to have python installed in their machines. This *could* create some friction, even though it's not the end of the world.

I wanted to ask you what would prefer:

1. keep `python` inside our project and update the `CONTRIBUTING.md` with mention of this script and saying that developers require having python installed

2. move the script to Rust

I vote for `2.`
</div>

The result of discussion is that the team would like to [move the python script](https://github.com/rome/tools/blob/main/crates/rslint_lexer/scripts/gen.py) to Rust.

The steps to move this script to Rust are:
- move the script inside the `xtask` folder, where we have all our internal scripts
- add a new command called `unicode`, which can be called with the following command `cargo xtask unicode`
- the new command will call the new script, which can live inside a single file or folder. I don't think it matters much as it's a small script (probably)
- the script will have to update the [`tables.rs` file](https://github.com/rome/tools/blob/main/crates/rslint_lexer/src/tables.rs)

It would be great if only new contributors would tackle this issue, as it's not a high priority task and it's really self contained. 

Any questions or doubts, please ask here!

**Comment by malobre** [comment]
I'm working on this in #1932.

**Comment by malobre** [comment]
FYI, dtolnay recently published [`unicode-ident`](https://github.com/dtolnay/unicode-ident) which has the same purpose as the file generated by the script I made in #1932 (i.e: provide a fn to check if a char is `ID_Start` or `ID_Continue`).

It would probably be best to migrate to this instead of relying on the script (better space and speed optimizations), the API is a drop-in replacement for the generated file (`fn(char) -> bool`, see [the doc](https://docs.rs/unicode-ident/latest/unicode_ident/index.html#functions)).

Should I open a new issue ?

**Comment by Boshen** [comment]
I made a fork of `unicode-xid` for `unicode-id`: https://crates.io/crates/unicode-id, it's being used in swc. 

Let me ask him for the best approach for not duplicating efforts, for all the JavaScript parsers to use. 

Question asked here: `https://github.com/dtolnay/unicode-ident/issues/1`
