### ISSUE TITLE
📎 Coverage: Run tests concurrently

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2011]
### Description

The `cargo coverage` commands uses a thread pool but spawn only a single task that then executes all the tests. 

The goal is to spawn a task for each file to run them concurrently and make use of the thread-pool (and existing channel).

**Comment by MichaReiser** [comment]
@xunilrj let me know if you already started working on it. I'm otherwise interested to take this on to gain some experience writing concurrent code in Rust.

**Comment by Boshen** [comment]
Since we are changing the coverage command, I have some proposals to make:
* change `let detailed = num_ran < 10;` to a flag
  * this will make investing errors easier when we combine it with a filter
* remove `indicatif::ProgressBar`, or at least the printing message bit
  * messages printed with indicatif can't be piped to a file, which makes things difficult
* add a flag to print the source code

**Comment by Boshen** [comment]
Wait ... doesn't 
```rust
    pool.scoped(|scope| {
        let pb = &pb;
        for file in files {
            let tx = tx.clone();

            scope.execute(move || {
                let res = run_test_file(file);
```

run all the tests in parallel?

**Comment by MichaReiser** [comment]
Oh, it may then just be that the TS tests aren't run in parallel. I'll do some refactorings to unify the two and we can then decide to make additional changes from there

**Comment by xunilrj** [comment]
> @xunilrj let me know if you already started working on it. I'm otherwise interested to take this on to gain some experience writing concurrent code in Rust.

No. You can do it.
