### ISSUE TITLE
Typescript: `abstract` classes

### ISSUE THREAD

**Issue by xunilrj** [rome/tools#2059]
- [x] Simple abstract class;
    - [x] With concrete members;
    - [x] With abstract members;
        - [x]  Fix ```conformance/classes/classDeclarations/classAbstractKeyword/classAbstractMethodWithImplementation.ts```;
- [x] ```abstract``` is a valid class name (even in TS) and a valid enum variant;
- [x] abstract classes must be exportable;
- Error Handling
    - [x] Abstract member should not have body;
    - abstract members should not appear in interfaces, non abstract classes and enums;
    - [x] private member cannot be abstract
        - [x] private name member cannot be abstract
    - [x] async member cannot be abstract
    - [x] abstract members should not be static
- [x] overloaded methods/constructors do not have body

**Comment by MichaReiser** [comment]
Let me share my thoughts around abstract members here as this will now be tackled as part of this issue. Feel free to follow another approach:

I considered re-using `MethodSignatureTypeMember`, `GetterSignatureTypeMember`, `SetterSignatureTypeMember` for abstract methods because they don't have a body
However, this comes with the downside that:
* These members must have an abstract token that is only valid inside classes but neither for types nor interfaces
* The naming isn't as nice anymore... `JsAnyClassMember` then contains `*TypeMember` variants

The reason why I wouldn't add `abstract` to the `ClassMember` is that the `body` is mandatory for non-abstract members. That's a constraint that we, so far, uphold. A mandatory node is always mandatory in all contexts. Furthermore, we already have many cases where a specific child isn't allowed but is otherwise considered optional (variable initializers, parameter initializers...)

**Comment by MichaReiser** [comment]
@xunilrj can we close this issue. I'll create new nones for the ambient parsing, `override` and the modifier order.

**Comment by xunilrj** [comment]
Needs improvement:

- [ ] Abstract members should not appear in interfaces, non abstract classes and enums;

```
error[SyntaxError]: ';' expected'
  ┌─ ts_interfaces_cannot_have_abstract_members.ts:2:14
  │
2 │     abstract prop: string;
  │              ^^^^ An explicit or implicit semicolon is expected here...

--
error[SyntaxError]: ';' expected'
  ┌─ ts_interfaces_cannot_have_abstract_members.ts:3:14
  │
3 │     abstract method(): string;
  │              ^^^^^^ An explicit or implicit semicolon is expected here...

--
error[SyntaxError]: index signature members cannot be abstract
  ┌─ ts_interfaces_cannot_have_abstract_members.ts:4:5
  │
4 │     abstract [index: number]: string
  │     ^^^^^^^^

--
error[SyntaxError]: ';' expected'
  ┌─ ts_interfaces_cannot_have_abstract_members.ts:5:14
  │
5 │     abstract get name(): string;
  │              ^^^ An explicit or implicit semicolon is expected here...

--
error[SyntaxError]: ';' expected'
  ┌─ ts_interfaces_cannot_have_abstract_members.ts:6:14
  │
6 │     abstract set name(v);
  │              ^^^ An explicit or implicit semicolon is expected here...

--
interface A {
    abstract prop: string;
    abstract method(): string;
    abstract [index: number]: string
    abstract get name(): string;
    abstract set name(v);
}
```
