### ISSUE TITLE
📎 Larger files for benchmark

### ISSUE THREAD

**Issue by Boshen** [rome/tools#2085]
### Description

The benchmark files are minified files, they are rather small for benchmark, I think we should change them to larger files, I have come up with the following:

```
https://cdn.jsdelivr.net/npm/d3@7.1.1/dist/d3.js
https://cdn.jsdelivr.net/npm/lodash@4.17.0/lodash.js
https://cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/build/pdf.js
https://cdn.jsdelivr.net/npm/react-dom@17.0.2/cjs/react-dom.development.js
https://cdn.jsdelivr.net/npm/svelte@3.46.4/compiler.js
https://cdn.jsdelivr.net/npm/three@0.137.5/build/three.js

559K d3.js
526K lodash.js
412K pdf.js
874K react-dom.development.js
1.1M compiler.js
1.1M three.js
```

**Comment by MichaReiser** [comment]
Welcome back @Boshen I hope you had a good time. 

Thanks for reviewing our benchmark files. I can see value in a more handpicked list of benchmark files but I would argue that having different library sizes provides additional signals 

Profiling small libraries can show if a change introduces any heavy upfront cost that doesn't depend on the size of the file. A high upfront cost before parsing any file can have a huge impact on a bundler because projects often have more small files than large ones (the large ones coming from libraries that rarely change and, thus, can be built once and be cached). 

Profiling medium, large, and particularly super large libraries can help to detect any algorithmic regressions. For example, if a change introduces heavy back-tracking or cloning of the parser state. 

We should probably also soon consider adding some TypeScript libraries, maybe even TypeScript itself.

**Comment by Boshen** [comment]
Good points, let's break up the files into:
1 small file < 100kb
1 medium file ~500kb
1 large file > 1mb
with js and ts for each size, so we have 6 files for benchmarks, about 2 minutes of coffee time.

We don't want to add too many files as the wait time is rather long.

And also, my proposal is to remove the minified files as our parser mainly targets unminified files.

**Comment by ematipico** [comment]
> Good points, let's break up the files into:
> 1 small file < 100kb
> 1 medium file ~500kb
> 1 large file > 1mb
> with js and ts for each size, so we have 6 files for benchmarks, about 2 minutes of coffee time.
> 
> We don't want to add too many files as the wait time is rather long.
> 
> And also, my proposal is to remove the minified files as our parser mainly targets unminified files, so the benchmark results can give us some real estimates of human waiting time.

The parser will also target minified files. Especially inside a bundler/package resolution situation. Imagine we have a dependency that requires a peer dependency, we need to have its AST in order to resolve that dependency correctly.

Everything boils down to the parser. So it's to target every typology of files we can

**Comment by xunilrj** [comment]
One thing we can do is have multiple libs.txt and we can bench them independently like:

```
> cargo bench_parser min
...
> cargo bench_parser big
...
> cargo bench_parser npmtop1k
```
