### ISSUE TITLE
📎 Automatic detection of source type

### ISSUE THREAD

**Issue by ematipico** [rome/tools#2194]
### Description

At the moment when parsing, we don't do any check on the files and we parse it as module. This is a source of issues for our parser. We should add a way to detect `SourceType` correctly

**Comment by MichaReiser** [comment]
Is the goal of this to detect the `SourceType` inside of the parser or in VS Code?

I'm not aware of a performant way to achieve this inside of the parser without having a second compilation pass (or parsing the file multiple times if we guessed incorrectly). The problem is that a module automatically becomes "strict" if there's any module syntax (`export`/`import`). That means, the parser now needs to go back and re-validate the already parsed syntax for any strict mode violations.

**Comment by ematipico** [comment]
The goal of this PR is just to correctly detect the language in a way that is more in line with the file itself, e.g. `.js` should have `SourceType.language == Langauge::JavaScript`. Nothing more, for now

We are not ready yet to "guess" the module kind unfortunately, for the time being. I would wait until we have a project detection (either `package.json` or `rome.json`). Doing two passes of the parser **might** be a **short term solution** that we could explore, maybe with a separate PR.
