### ISSUE TITLE
🐛 Stack Overflow When Formatting Rome Codebase

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2356]
### Environment information

```bash
MacBook Air (M1, 2020) 8 GB RAM

Built cli at commit e7e08192aeeba4a06309e5acd96b96cf89080001 on release
```

### What happened?

Ran `rome format .` at root of tools repo. Received:

```
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
zsh: abort      rome format .
```

### Expected result

We should not stack overflow

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
I suppose you tried a global installation?

**Comment by leops** [comment]
> It seems we don't ignore folders like `node_modules`, this could leads to tons of files loaded in virtual file system?

The `node_modules` and `.git` directories are statically ignored in [`crates\rome_fs\src\fs\os.rs:117`](https://github.com/rome/tools/blob/main/crates/rome_fs/src/fs/os.rs#L117), but in general loading too many files should result in an "out of memory" error and not a stack overflow. I haven't reproduced the error yet, but my theory is that it's reaching into the parser test cases and hitting a file with deeply nested expressions (I know the TypeScript tests have one of these)

**Comment by MichaReiser** [comment]
@NicholasLYang I'm unable to reproduce this issue, even when checking out #e7e08192aeeba4a06309e5acd96b96cf89080001. My understanding is that you did run `cargo run -p rome_cli --release -- format ../rome-classic/` or did you run the command formatting all files in rusty rome?

**Comment by NicholasLYang** [comment]
I ran it on the current repo, not the RomeJS repo. So, to be fair, that's a lot of code, about 77341 files according to a quick grep. I guess it's not a huge deal but it might be worth seeing what our limit is for number of files

**Comment by leops** [comment]
> I ran it on the current repo, not the RomeJS repo. So, to be fair, that's a lot of code, about 77341 files according to a quick grep. I guess it's not a huge deal but it might be worth seeing what our limit is for number of files

There isn't really a hard limit for the number of files we can process, the time it takes for the CLI to run should just scale somewhat linearly. Of course this is an approximation because the time it takes to process one file isn't constant, non-JS files get rejected instantly while very large files (eg. minified bundles) take longer to process.

Anyway I finally got the TypeScript submodules checked out, running the CLI with a debugger attached reveals it's overflowing on a very deep recursive binary expression. Fortunately since those expressions are handled in a special utility it should be easier to flatten the algorithm into a loop instead of using recursion.

![binary_expression](https://user-images.githubusercontent.com/1895119/162386515-fe13271f-5a48-4307-b467-84b65b424a81.png)

**Comment by ematipico** [comment]
That's neat! I think can change it!
