### ISSUE TITLE
Destructuring arguments

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#2439]
Rome's formatter always tries to fit all restructuring members on a new line whereas Prettier has a heuristic to special print restructuring patterns when it's the only function argument [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=true&sourceType=module#LwAvACAATwBuAGwAeQAgAGEAcgBnAHUAbQBlAG4AdAAsACAAdwBoAG8AbABlACAAZABlAGYAaQBuAGkAdABpAG8AbgAgAGQAbwBlAHMAbgAnAHQAIABmAGkAdAAuACAAUAByAGkAbgB0ACAAWwAgAG8AcgAgAHsAIABvAG4AIABzAGEAbQBlACAAbABpAG4AZQAsACAAbQBlAG0AYgBlAHIAcwAgAG8AbgAgAGEAIABuAGUAdwAgAGwAaQBuAGUAIABlAGEAYwBoAAoAZgB1AG4AYwB0AGkAbwBuACAAZQB4AGMAbAB1AGQAZQBGAGkAcgBzAHQARgBpAHYAZQBSAGUAcwB1AGwAdABzADMAKABbAAoAIAAgAGYAaQByAHMAdABSAGUAcwB1AGwAdAAsACAAcwBlAGMAbwBuAGQAUgBlAHMAdQBsAHQALAAgAHQAaABpAHIAZABSAGUAcwB1AGwAdAAsACAAZgBvAHUAcgB0AGgAUgBlAHMAdQBsAHQALAAgAGYAaQBmAHQAaABSAGUAcwB1AGwAdAAsACAALgAuAC4AcgBlAHMAdABdACAAPQAgAFsAMQAsACAAMgAsACAAMwAsACAANAAsACAANQBdACkAIAB7AAoAfQAKAAoACgBmAHUAbgBjAHQAaQBvAG4AIABTAHQAYQB0AGUAbABlAHMAcwBGAHUAbgBjAHQAaQBvAG4AYQBsAEMAbwBtAHAAbwBuAGUAbgB0ACgAewAKACAAIABpAHMAQQBjAHQAaQB2AGUALAAKACAAIABvAG4ARgBpAGwAdABlAHIAcwBVAHAAZABhAHQAZQBkACwACgAgACAAbwBuAFMAZQBsAGUAYwB0ACwACgB9ACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAPABkAGkAdgAgAC8APgAKAH0ACgAKAC8ALwAgAEkAZgAgAHQAaABlACAAZgB1AG4AYwB0AGkAbwBuACAAaABhAHMAIABtAG8AcgBlACAAdABoAGEAbgAgAG8AbgBlACAAYQByAGcAdQBtAGUAbgB0ACwAIAB0AHIAeQAgAHQAbwAgAGYAaQB0ACAAZABlAHMAdAByAHUAYwB0AHUAcgBpAG4AZwAgAG8AbgAgAGEAIABzAGkAbgBnAGwAZQAgAGwAaQBuAGUAIAAKAC8ALwAgAEkAZgAgAG4AbwB0ACwAIABwAHIAaQBuAHQAIABlAGEAYwBoACAAbQBlAG0AYgBlAHIAIABvAG4AIAB0AGgAZQBpAHIAIABvAHcAbgAgAGwAaQBuAGUALgAgAAoAZgB1AG4AYwB0AGkAbwBuACAAZQB4AGMAbAB1AGQAZQBGAGkAcgBzAHQARgBpAHYAZQBSAGUAcwB1AGwAdABzADMAKABbAAoAIAAgAGYAaQByAHMAdABSAGUAcwB1AGwAdAAsACAAcwBlAGMAbwBuAGQAUgBlAHMAdQBsAHQALAAgAHQAaABpAHIAZABSAGUAcwB1AGwAdAAsACAAZgBvAHUAcgB0AGgAUgBlAHMAdQBsAHQALAAgAGYAaQBmAHQAaABSAGUAcwB1AGwAdAAsACAALgAuAC4AcgBlAHMAdABdACAAPQAgAFsAMQAsACAAMgAsACAAMwAsACAANAAsACAANQBdACwAIAB0AGUAcwB0ACwAIAB0AGgAaQByAGQAKQAgAHsACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABTAHQAYQB0AGUAbABlAHMAcwBGAHUAbgBjAHQAaQBvAG4AYQBsAEMAbwBtAHAAbwBuAGUAbgB0ADIAKAB7AAoAIAAgAGkAcwBBAGMAdABpAHYAZQAsAAoAIAAgAG8AbgBDAGEAbgBjAGUAbAAsAAoAIAAgAHMAZQBhAHIAYwBoAEYAaQBsAHQAZQByAHMALAAKACAAIAB0AGkAdABsAGUALAAKACAAIABpAHQAZQBtAHMALAAKAH0ALAAgAG0AbwByAGUAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAA8AGQAaQB2ACAALwA+AAoAfQAKAAoAZgB1AG4AYwB0AGkAbwBuACAAUwB0AGEAdABlAGwAZQBzAHMARgB1AG4AYwB0AGkAbwBuAGEAbABDAG8AbQBwAG8AbgBlAG4AdAAyACgAZgBpAHIAcwB0ACwAIAB7AAoAIAAgAGkAcwBBAGMAdABpAHYAZQAsAAoAIAAgAG8AbgBDAGEAbgBjAGUAbAAsAAoAIAAgAHMAZQBhAHIAYwBoAEYAaQBsAHQAZQByAHMALAAKACAAIAB0AGkAdABsAGUALAAKACAAIABpAHQAZQBtAHMALAAKAH0AKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAA8AGQAaQB2ACAALwA+AAoAfQA=)

## Input

```ts
// Only argument, whole definition doesn't fit. Print [ or { on same line, members on a new line each
function excludeFirstFiveResults3([
  firstResult, secondResult, thirdResult, fourthResult, fifthResult, ...rest] = [1, 2, 3, 4, 5]) {
}


function StatelessFunctionalComponent({
  isActive,
  onFiltersUpdated,
  onSelect,
}) {
  return <div />
}

// If the function has more than one argument, try to fit destructuring on a single line 
// If not, print each member on their own line. 
function excludeFirstFiveResults3([
  firstResult, secondResult, thirdResult, fourthResult, fifthResult, ...rest] = [1, 2, 3, 4, 5], test, third) {
}

function StatelessFunctionalComponent2({
  isActive,
  onCancel,
  searchFilters,
  title,
  items,
}, more) {
  return <div />
}

function StatelessFunctionalComponent2(first, {
  isActive,
  onCancel,
  searchFilters,
  title,
  items,
}) {
  return <div />
}
```

## Prettier

```ts
// Only argument, whole definition doesn't fit. Print [ or { on same line, members on a new line each
function excludeFirstFiveResults3(
  [
    firstResult,
    secondResult,
    thirdResult,
    fourthResult,
    fifthResult,
    ...rest
  ] = [1, 2, 3, 4, 5]
) {}

function StatelessFunctionalComponent({
  isActive,
  onFiltersUpdated,
  onSelect,
}) {
  return <div />;
}

// If the function has more than one argument, try to fit destructuring on a single line
// If not, print each member on their own line.
function excludeFirstFiveResults3(
  [
    firstResult,
    secondResult,
    thirdResult,
    fourthResult,
    fifthResult,
    ...rest
  ] = [1, 2, 3, 4, 5],
  test,
  third
) {}

function StatelessFunctionalComponent2(
  { isActive, onCancel, searchFilters, title, items },
  more
) {
  return <div />;
}

function StatelessFunctionalComponent2(
  first,
  { isActive, onCancel, searchFilters, title, items }
) {
  return <div />;
}
```

## Rome

```ts
// Only argument, whole definition doesn't fit. Print [ or { on same line, members on a new line each
function excludeFirstFiveResults3(
  [firstResult, secondResult, thirdResult, fourthResult, fifthResult, ...rest] = [
    1, 2, 3, 4, 5,
  ],
) {}

function StatelessFunctionalComponent({ isActive, onFiltersUpdated, onSelect }) {
  return <div />;
}

// If the function has more than one argument, try to fit destructuring on a single line
// If not, print each member on their own line.
function excludeFirstFiveResults3(
  [firstResult, secondResult, thirdResult, fourthResult, fifthResult, ...rest] = [
    1, 2, 3, 4, 5,
  ],
  test,
  third,
) {}

function StatelessFunctionalComponent2(
  { isActive, onCancel, searchFilters, title, items },
  more,
) {
  return <div />;
}

function StatelessFunctionalComponent2(
  first,
  { isActive, onCancel, searchFilters, title, items },
) {
  return <div />;
}

```

## Expected

Rome's formatting to match Prettier's

**Comment by ematipico** [comment]
Actually, this is the expected behaviour and the issue not the destructuring per se. We are hitting the known limitation that Leo already talked about.

Try this instead and you will see that we actually print correctly: [Playground](https://play.rome.tools/?lineWidth=80&indentStyle=space&quoteStyle=double&indentWidth=2&typescript=true&jsx=false&sourceType=module#CgAvAC8AIABJAGYAIAB0AGgAZQAgAGYAdQBuAGMAdABpAG8AbgAgAGgAYQBzACAAbQBvAHIAZQAgAHQAaABhAG4AIABvAG4AZQAgAGEAcgBnAHUAbQBlAG4AdAAsACAAdAByAHkAIAB0AG8AIABmAGkAdAAgAGQAZQBzAHQAcgB1AGMAdAB1AHIAaQBuAGcAIABvAG4AIABhACAAcwBpAG4AZwBsAGUAIABsAGkAbgBlAAoALwAvACAASQBmACAAbgBvAHQALAAgAHAAcgBpAG4AdAAgAGUAYQBjAGgAIABtAGUAbQBiAGUAcgAgAG8AbgAgAHQAaABlAGkAcgAgAG8AdwBuACAAbABpAG4AZQAuAAoAZgB1AG4AYwB0AGkAbwBuACAAZQB4AGMAbAB1AGQAZQBGAGkAcgBzAHQARgBpAHYAZQBSAGUAcwB1AGwAdABzADMAKAAKACAAIABbAAoAIAAgACAAIABmAGkAcgBzAHQAUgBlAHMAdQBsAHQALAAKACAAIAAgACAAdABoAGkAcgBkAFIAZQBzAHUAbAB0ACwACgAgACAAIAAgAGYAbwB1AHIAdABoAFIAZQBzAHUAbAB0ACwACgAgACAAIAAgAGYAaQBmAHQAaABSAGUAcwB1AGwAdAAsAAoAIAAgACAAIAAuAC4ALgByAGUAcwB0AAoAIAAgAF0AIAA9ACAAWwAxACwAIAAyACwAIAAzACwAIAA0ACwAIAA1AF0ALAAKACAAIAB0AGUAcwB0ACwACgAgACAAdABoAGkAcgBkAAoAKQAgAHsAfQAKAAoALwAvACAASQBmACAAdABoAGUAIABmAHUAbgBjAHQAaQBvAG4AIABoAGEAcwAgAG0AbwByAGUAIAB0AGgAYQBuACAAbwBuAGUAIABhAHIAZwB1AG0AZQBuAHQALAAgAHQAcgB5ACAAdABvACAAZgBpAHQAIABkAGUAcwB0AHIAdQBjAHQAdQByAGkAbgBnACAAbwBuACAAYQAgAHMAaQBuAGcAbABlACAAbABpAG4AZQAKAC8ALwAgAEkAZgAgAG4AbwB0ACwAIABwAHIAaQBuAHQAIABlAGEAYwBoACAAbQBlAG0AYgBlAHIAIABvAG4AIAB0AGgAZQBpAHIAIABvAHcAbgAgAGwAaQBuAGUALgAKAGYAdQBuAGMAdABpAG8AbgAgAGUAeABjAGwAdQBkAGUARgBpAHIAcwB0AEYAaQB2AGUAUgBlAHMAdQBsAHQAcwAzACgACgAgACAAWwAKACAAIAAgACAAZgBpAHIAcwB0AFIAZQBzAHUAbAB0ACwACgAgACAAIAAgAHMAZQBjAG8AbgBkAFIAZQBzAHUAbAB0ACwACgAgACAAIAAgAHQAaABpAHIAZABSAGUAcwB1AGwAdAAsAAoAIAAgACAAIABmAG8AdQByAHQAaABSAGUAcwB1AGwAdAAsAAoAIAAgACAAIABmAGkAZgB0AGgAUgBlAHMAdQBsAHQALAAKACAAIAAgACAAcwBpAHgAdABoAFIAZQBzAHUAbAB0ACwACgAgACAAIAAgAC4ALgAuAHIAZQBzAHQACgAgACAAXQAgAD0AIABbADEALAAgADIALAAgADMALAAgADQALAAgADUAXQAsAAoAIAAgAHQAZQBzAHQALAAKACAAIAB0AGgAaQByAGQACgApACAAewB9AA==)

**Comment by MichaReiser** [comment]
@ematipico can you elaborate? Prettier has very specific formatting if the only parameter is an object or array pattern that Rome doesn't support.

**Comment by ematipico** [comment]
[Here's a link](https://discord.com/channels/678763474494423051/960684139873435708/960805782939656192) to the message.

Maybe you're talking about a specific case that I can't see. If you add `sixthResult` to the destructuring, you will see that we format like prettier.

**Comment by MichaReiser** [comment]
> [Here's a link](https://discord.com/channels/678763474494423051/960684139873435708/960805782939656192) to the message. In this case the closing `]` it's not considered inside the grouping when considering the max width.
> 
> Maybe you're talking about a specific case that I can't see. If you add `sixthResult` to the destructuring, you will see that we format like prettier.

[This](http://localhost:3000/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#ZgB1AG4AYwB0AGkAbwBuACAAUwB0AGEAdABlAGwAZQBzAHMARgB1AG4AYwB0AGkAbwBuAGEAbABDAG8AbQBwAG8AbgBlAG4AdAAoAHsACgAgACAAaQBzAEEAYwB0AGkAdgBlACwACgAgACAAbwBuAEYAaQBsAHQAZQByAHMAVQBwAGQAYQB0AGUAZAAsAAoAIAAgAG8AbgBTAGUAbABlAGMAdAAsAAoAfQApACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAIAAvAD4AOwAKAH0A)

**Comment by ematipico** [comment]
> > [Here's a link](https://discord.com/channels/678763474494423051/960684139873435708/960805782939656192) to the message. In this case the closing `]` it's not considered inside the grouping when considering the max width.
> > Maybe you're talking about a specific case that I can't see. If you add `sixthResult` to the destructuring, you will see that we format like prettier.
> 
> [This](http://localhost:3000/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#ZgB1AG4AYwB0AGkAbwBuACAAUwB0AGEAdABlAGwAZQBzAHMARgB1AG4AYwB0AGkAbwBuAGEAbABDAG8AbQBwAG8AbgBlAG4AdAAoAHsACgAgACAAaQBzAEEAYwB0AGkAdgBlACwACgAgACAAbwBuAEYAaQBsAHQAZQByAHMAVQBwAGQAYQB0AGUAZAAsAAoAIAAgAG8AbgBTAGUAbABlAGMAdAAsAAoAfQApACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAIAAvAD4AOwAKAH0A)
> 
> > Prettier has a heuristic to special print restructuring patterns when it's the **only** function argument
> 
> The difference is that Prettier breaks the argument if the whole function header doesn't fit, and not just the parameters. This isn't related to the case where Rome prints a few characters over the line width.


Can you add the case into the description? Because **this actually highlights** the issue, but the case the example I shared actually hits the limitation we just spoke and I think it is not related to this issue in particular. [They are two different cases](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAyjAIbwA2cAzlQGKbZ5QnkDCEAtgA7QIwAUwADpR8+HFQCCjAG5wANCLHRaOcvABOVAKpcAJmTh75Y0-iX5ohOJWyKoAXwCU+YaPwa4MdBtEAePRwZfAB6AD4AbhEHEREMLFwCOAAPMHJ0PThVLRhVOQAlanR1KgBmfgsAbVQcHMKqYpgTKjhIKD16xpMYAAtajqL1E1QIH17Oofwa1HHBpvwAOiXPKhgAXXwAXnxKizEARhMAJhNSkwAWEwBWezE1+xdgBxB5EAguRKgqZFASDQ0IAB3AAKfwQ3xQLEBJAAnt9XgAjDQkMAAay8hBIHDgABkcFA4MhUCwWojkWiMVwUfiAObIGAadAKEBwDgIoyZPQ4khQGnoEg0rIQDQcMi4XnIEAkdAwCAvEA9GAccgAdT68CoVLAcGsXxwuBk+phkrANHl+JaGhgwORNNFRJJzIAVlRkoRaZQAIroCDwB3kUkgKlaOAaSUIkjs8jyrgafEwFU4PS9ZAADgADK9YxAWirkVxJbHqKG5PKAI4++A294QqVUAC0BKMRnlngrtTgNoF9qQxIDzJaHBw9MZA49cG9vsJvcdr1ICMTyZ6yBOIAZJDUtPYHB7LKoV3l6BaABVIxC+4GZEyAJLtPiEMBxj6SdrEGGUf0tBwOIA), the IR is different for Prettier too.

**Comment by MichaReiser** [comment]
> > > [Here's a link](https://discord.com/channels/678763474494423051/960684139873435708/960805782939656192) to the message. In this case the closing `]` it's not considered inside the grouping when considering the max width.
> > > Maybe you're talking about a specific case that I can't see. If you add `sixthResult` to the destructuring, you will see that we format like prettier.
> > 
> > 
> > [This](http://localhost:3000/?lineWidth=80&indentStyle=tab&quoteStyle=double&indentWidth=2&typescript=false&jsx=false&sourceType=module#ZgB1AG4AYwB0AGkAbwBuACAAUwB0AGEAdABlAGwAZQBzAHMARgB1AG4AYwB0AGkAbwBuAGEAbABDAG8AbQBwAG8AbgBlAG4AdAAoAHsACgAgACAAaQBzAEEAYwB0AGkAdgBlACwACgAgACAAbwBuAEYAaQBsAHQAZQByAHMAVQBwAGQAYQB0AGUAZAAsAAoAIAAgAG8AbgBTAGUAbABlAGMAdAAsAAoAfQApACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAIAAvAD4AOwAKAH0A)
> > > Prettier has a heuristic to special print restructuring patterns when it's the **only** function argument
> > 
> > 
> > The difference is that Prettier breaks the argument if the whole function header doesn't fit, and not just the parameters. This isn't related to the case where Rome prints a few characters over the line width.
> 
> Can you add the case into the description? Because **this actually highlights** the issue, but the case the example I shared actually hits the limitation we just spoke and I think it is not related to this issue in particular. [They are two different cases](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAyjAIbwA2cAzlQGKbZ5QnkDCEAtgA7QIwAUwADpR8+HFQCCjAG5wANCLHRaOcvABOVAKpcAJmTh75Y0-iX5ohOJWyKoAXwCU+YaPwa4MdBtEAePRwZfAB6AD4AbhEHEREMLFwCOAAPMHJ0PThVLRhVOQAlanR1KgBmfgsAbVQcHMKqYpgTKjhIKD16xpMYAAtajqL1E1QIH17Oofwa1HHBpvwAOiXPKhgAXXwAXnxKizEARhMAJhNSkwAWEwBWezE1+xdgBxB5EAguRKgqZFASDQ0IAB3AAKfwQ3xQLEBJAAnt9XgAjDQkMAAay8hBIHDgABkcFA4MhUCwWojkWiMVwUfiAObIGAadAKEBwDgIoyZPQ4khQGnoEg0rIQDQcMi4XnIEAkdAwCAvEA9GAccgAdT68CoVLAcGsXxwuBk+phkrANHl+JaGhgwORNNFRJJzIAVlRkoRaZQAIroCDwB3kUkgKlaOAaSUIkjs8jyrgafEwFU4PS9ZAADgADK9YxAWirkVxJbHqKG5PKAI4++A294QqVUAC0BKMRnlngrtTgNoF9qQxIDzJaHBw9MZA49cG9vsJvcdr1ICMTyZ6yBOIAZJDUtPYHB7LKoV3l6BaABVIxC+4GZEyAJLtPiEMBxj6SdrEGGUf0tBwOIA), the IR is different for Prettier too.

The case is mentioned in the description and this issue aren't about specific technical limitations but how our formatter formats things differently. That means, who ever works on this needs to take a closer look on how patterns are formatted in function parameters. If we have to create issue for every distinct case then we end up with 100 of issues and it would take me weeks.
