### ISSUE TITLE
📎 Allow JSX in `.js` files

### ISSUE THREAD

**Issue by NicholasLYang** [rome/tools#2625]
### Description

We should consider adding JSX support by default when parsing a `.js` file. It's quite common for `.js` files to contain JSX. Giving errors such as:

```
error[SyntaxError]: type assertion are a TypeScript only feature. Convert your file to a TypeScript file or remove the syntax.
   ┌─ src/DebugOffset.js:31:5
   │
31 │     <div style={{ ...markerStyles, top, }}>
   │     ^^^^^^^^^^ TypeScript only syntax
```

Is not great UX imo.

Alternatively, we could have a feature that parses as JS, then bails to JSX. But I don't see a reason to not allow JSX for all situations.

**Comment by MichaReiser** [comment]
I agree that we could do better and this error message isn't ideal. However, I would refrain from enabling JSX for JS files by default because.

## Syntax Ambiguity

The issue with JSX is that some syntax is ambiguous, completely valid JS/TS code now becomes invalid. 

```js
 // Valid JS but not JSX
3 <a> c</test

// Not allowed in TSX
<number> x // You need to use x as number

// Invalid in TSX
<T>(x: T) => x // You have to write <T, >(x: T) => x
```

Agreed, the limitations for TS are more significant than for JS but I think it's more important that Rome is consistent. That means, either enable JSX for `ts` and `js` files or don't. And to that point, we should be in line with TypeScript and they [decided against](https://github.com/microsoft/TypeScript/issues/44442) enabling JSX by default. 

Somewhat related to ambiguity. Enabling JSX results in worse error messages because there are situations where the parser (at least our current implementation) is no longer able to predict what the user meant. That means, enabling JSX gives a worse experience for everyone not using JSX.

## Performance penalty

I would refrain from using double parsing whenever possible because it gives JSX users a worse user experience in the long term. Formatting their project will take twice as long as it should, just because we didn't recommend them to enable JSX for their project. 

## JSX Transpilation
Transforming JSX requires knowledge about the target framework. That means we may be able to delay an explicit configuration until we start working on transpilation but it will not prevent us from needing one in the long term. 


## Proposal

My proposal is to better guide people who use Rome. The workflow I envision is that Rome asks you if you want to enable JSX and proposes the right dialect if it is fairly certain that you used JSX in one of your files. Not only that, it could then inspect the package.json file to propose the right dialect but lets the user confirm what framework they're using.

**Comment by strager** [comment]
@MichaReiser Did your first example publish incorrectly? It's not valid JavaScript in any parser I tried.
```js
 // Valid JS but not JSX
3 <a> c</test
```

**Comment by MichaReiser** [comment]
@NicholasLYang I quickly looked into how Prettier provides this functionality and it does not. It defers the problem to the parser. 

If you run `prettier --parser typescript index.js` against a file that contains JSX then prettier fails. 

Babel seems to be more permissive overall: For example, it allows

```
3 <a> c</a/
```

The issue with this syntax is that every opening element now introduces a potential back-tracking point in case it turns out that the closing tag is a regular expression and not a regular element name. Taking a snapshot isn't crazy expensive but doing it as frequently as for every jsx opening element will clearly have a cost. 

@strager yeah sorry, it requires a closing `/`. I'm also not entirely sure if it is indeed invalid syntax. E.g. Babel is fine with it (but babel allows much that isn't spec compliant), but TypeScript doesn't parse it.

**Comment by strager** [comment]
> E.g. Babel is fine with it (but babel allows much that isn't spec compliant), but TypeScript doesn't parse it.

It looks like TypeScript does parse the code if JSX mode is disabled: https://www.typescriptlang.org/play?jsx=0#code/DYUwLgBAhhC8EEYDcAoUkDGdGpQZggB4oA+CDQgeikqA

> The issue with JSX is that some syntax is ambiguous, completely valid JS/TS code now becomes invalid.

I checked this code with all the parsers in astexplorer.net:
```js
3 <a> c</test/
let c = <test/>;
```
Only meriyah and TypeScript were confused by the first line when JSX was enabled. I think you're talking about a bug in a specific parser, not an ambiguity in the grammar:
<table>
<tr><th>parser</th><th>line 1</th><th>line 2</th></tr>
<tr><th>acorn-8.3.0 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>acorn-8.3.0 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>@babel/eslint-parser-7.13.14</th><td>ok</td><td>ok</td></tr>
<tr><th>babel-eslint9-9.0.0</th><td>ok</td><td>ok</td></tr>
<tr><th>@babel/parser-7.16.12 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>@babel/parser-7.16.12 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>esformatter-1.0.0</th><td>ok</td><td>ok</td></tr>
<tr><th>espree-6.2.1 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>espree-6.2.1 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>esprima-4.0.1 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>esprima-4.0.1 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>flow-0.144.0</th><td>ok</td><td>ok</td></tr>
<tr><th>hermes-parser-0.4.7</th><td>ok</td><td>ok</td></tr>
<tr><th>meriyah-4.2.0 +jsx</th><td>error</td><td>ok</td></tr>
<tr><th>meriyah-4.2.0 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>recast-0.21.1 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>recast-0.21.1 -jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>seafox-1.7.1</th><td>ok</td><td>error</td></tr>
<tr><th>shift-7.0.0</th><td>ok</td><td>error</td></tr>
<tr><th>swc-1.2.146 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>swc-1.2.146 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>tenko-1.1.0</th><td>ok</td><td>error</td></tr>
<tr><th>traceur-0.0.111 +jsx</th><td>ok</td><td>ok</td></tr>
<tr><th>traceur-0.0.111 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>@typescript-eslint/parser-5.8.1 +jsx</th><td>error</td><td>ok</td></tr>
<tr><th>@typescript-eslint/parser-5.8.1 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>typescript-4.0.3 +jsx</th><td>error</td><td>ok</td></tr>
<tr><th>typescript-4.0.3 -jsx</th><td>ok</td><td>error</td></tr>
<tr><th>uglify-js-3.3.9</th><td>ok</td><td>error</td></tr>
</table>

**Comment by MichaReiser** [comment]
@strager  Thanks for checking the syntax for every parser.

For `3 <a> c</test/` yes, this is more a technical decision we need to make. 

> The issue with this syntax is that every opening element now introduces a potential back-tracking point in case it turns out that the closing tag is a regular expression and not a regular element name. Taking a snapshot isn't crazy expensive but doing it as frequently as for every jsx opening element will clearly have a cost.

We may be able to optimise this to only take the snapshot at the start of a JSX expression. But someone would need to look into how this affects performance and error recoverability (having JSX enabled means that the parser must short-circuit in some cases). 

The problem remains with TS where TS and TS + JSX has different syntax.

**Comment by MichaReiser** [comment]
Better error recovery is the reason why TypeScript & Rome doesn't parse this out:

https://github.com/rome/tools/blob/cc2a6466e969763be295312cb2a235b5087ac17f/crates/rome_js_parser/src/syntax/expr.rs#L461-L475


For `<test>{ 4 + 3</test>`:

**Babel**

```
Unterminated regular expression. (1:15)
```

**Rome**

```
error[SyntaxError]: expected `'}'` but instead found `<`
  ┌─ main.js:1:14
  │
1 │ <test>{ 4 + 3</test>
  │              ^ unexpected
```

**Comment by MichaReiser** [comment]
Oh, I was wrong. 

```js
yarn run tsc test.js --allowJs --noEmit
```

Emits no errors 

Let's do it! Should be straightforward to change in 

https://github.com/rome/tools/blob/0e225225906ac8b3a45f09007b686d8669f1d078/crates/rome_js_syntax/src/source_type.rs#L230-L251

Not sure if we should also change the helpers

https://github.com/rome/tools/blob/0e225225906ac8b3a45f09007b686d8669f1d078/crates/rome_js_syntax/src/source_type.rs#L114-L127

**Comment by ematipico** [comment]
I am of the idea that should follow TypeScript footsteps and allow JSX syntax only on .jsx files.

Having JSX on .js files is an old behaviour of 5/6 years ago where Babel was the only tool in town to be eligible of these kind of compilations.

Also, Babel is a tool for specific usage and sometimes it's not spec compliant for specific reason. We are not Babel.

Now the tools changed and the mindset shifted a bit. We have JSX supported by other tools (not just Babel), TS has become defacto an informal standard for type check, where it brought its own rules which people are following without many questions (.ts VS .tsx).

Also, we have a different mission compared to Babel (for example), which are error recovery, IDE  and performance. Have you ever tried to write JSX in a JavaScript file inside a IntelliJ IDE? It asks to convert it .jsx, probably for a reason.

If allowing JSX by default inside JavaScript files penalize one of these things above, we should not do it, regardless of what people's habit is.

 It might slow down the adoption, but if changing the file extension is better than having slower compilation, I'd say the people can accept this barging on the long run.

**Comment by ematipico** [comment]
Sure, if that's what TypeScript parser is doing, I don't see any reason why not (and we don't lose in performance).
