### ISSUE TITLE
📎 JSON Parser and Formatter

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rome/tools#2786]
### Description

Part of https://github.com/rome/tools/issues/2351.

I split the task into four parts:

- [ ] Implement JSON Parser without error recovery.
- [ ] Add error recovery.
- [ ] Implementing JSON formatting, port prettier test case
- [ ] Make the prettier compatibility reaching 100% as possible as we could.

**Comment by ematipico** [comment]
I would suggest to split off parser and formatter. These two tasks are not related and they should be implemented separately, plus there's already an umbrella issue to track these.  ( #2570 and #2351 ).

If this issue was created to track the works around the parser, then I would suggest the following:
- implement basic lexer, only UTF-8 handling
- implement a basic parser, only UTF-8, by parsing a basic object and string literal/boolean
- then objects and arrays 


Th error recovery should be done as last part, once we cover all the happy paths and then we cover all the syntax errors. Once that is done, the error recovery can be implemented.

**Comment by IWANABETHATGUY** [comment]
> 

Thanks, I would close this , and split the parser task under https://github.com/rome/tools/issues/2351
