### ISSUE TITLE
🐛 This variable is unused when import type from package then export that

### ISSUE THREAD

**Issue by harrytran998** [rome/tools#3193]
### Environment information

```bash
System:
    OS: macOS 12.3.1
  Binaries:
    Node: 18.6.0 - /usr/local/bin/node
    Yarn: 3.2.2 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 100.0
    Safari: 15.4
```

### What happened?

![image](https://user-images.githubusercontent.com/24296018/189365082-53c64d4d-a36b-4418-b173-0fca86e65c59.png)

```
import {
	createTheme,
	darken,
	lighten,
	styled,
	ThemeProvider,
	useTheme,
	type SxProps,
	type Theme,
} from '@mui/material/styles';

export {
	ThemeProvider,
	styled,
	alphaHex,
	lighten,
	darken,
	COLOR,
	ColorPalettes,
	useTheme,
	type SxProps,
	type Theme,
};
```

### Expected result

I hope this will resolve 😆. Thank the team for the hard work!

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by IWANABETHATGUY** [comment]
This bugs seems already fixed in main branch. 
https://play.rome.tools/?code=import+%7B%0A%09createTheme%2C%0A%09darken%2C%0A%09lighten%2C%0A%09styled%2C%0A%09ThemeProvider%2C%0A%09useTheme%2C%0A%09type+SxProps%2C%0A%09type+Theme%2C%0A%7D+from+%27%40mui%2Fmaterial%2Fstyles%27%3B%0A%0Aexport+%7B%0A%09ThemeProvider%2C%0A%09styled%2C%0A%09alphaHex%2C%0A%09lighten%2C%0A%09darken%2C%0A%09COLOR%2C%0A%09ColorPalettes%2C%0A%09useTheme%2C%0A%09type+SxProps%2C%0A%09type+Theme%2C%0A%7D%3B&lineWidth=80&indentStyle=tab&quoteStyle=double&quoteProperties=as-needed&indentWidth=2&sourceType=module&typescript=true&jsx=false#aQBtAHAAbwByAHQAIAB7AAoACQBjAHIAZQBhAHQAZQBUAGgAZQBtAGUALAAKAAkAZABhAHIAawBlAG4ALAAKAAkAbABpAGcAaAB0AGUAbgAsAAoACQBzAHQAeQBsAGUAZAAsAAoACQBUAGgAZQBtAGUAUAByAG8AdgBpAGQAZQByACwACgAJAHUAcwBlAFQAaABlAG0AZQAsAAoACQB0AHkAcABlACAAUwB4AFAAcgBvAHAAcwAsAAoACQB0AHkAcABlACAAVABoAGUAbQBlACwACgB9ACAAZgByAG8AbQAgACcAQABtAHUAaQAvAG0AYQB0AGUAcgBpAGEAbAAvAHMAdAB5AGwAZQBzACcAOwAKAAoAZQB4AHAAbwByAHQAIAB7AAoACQBUAGgAZQBtAGUAUAByAG8AdgBpAGQAZQByACwACgAJAHMAdAB5AGwAZQBkACwACgAJAGEAbABwAGgAYQBIAGUAeAAsAAoACQBsAGkAZwBoAHQAZQBuACwACgAJAGQAYQByAGsAZQBuACwACgAJAEMATwBMAE8AUgAsAAoACQBDAG8AbABvAHIAUABhAGwAZQB0AHQAZQBzACwACgAJAHUAcwBlAFQAaABlAG0AZQAsAAoACQB0AHkAcABlACAAUwB4AFAAcgBvAHAAcwAsAAoACQB0AHkAcABlACAAVABoAGUAbQBlACwACgB9ADsA

**Comment by harrytran998** [comment]
Thanks for your reply - After I upgrade the latest rome version `0.9.2-next' --> It worked. Thank.
