### ISSUE TITLE
🐛 Confusing error when running `rome check` with a directory

### ISSUE THREAD

**Issue by sebmck** [rome/tools#3329]
When I run `rome check .` I expected it to use the current directory and only lint valid files. However what happens is that it ends up erroring on the first file that we don't support. eg. I get the output:

```
./infra/terraform/.terraform/providers/registry.terraform.io/go-gandi/gandi/2.0.1/darwin_arm64 internalError/fs

  ✖ unhandled file type


Checked 0 files in 13ms
```

This isn't very helpful and it would be nice if when exploding a directory pattern on the CLI we filter it to supported files only.

I labeled this as a bug as this feels like some extraordinarily unexpected behaviour.

**Comment by leops** [comment]
This is one really poorly worded diagnostic that I need to rewrite, it generally gets emitted when the filesystem traversal finds a symbolic link as we currently ignore them because they could lead to an infinite traversal loop. I'm not sure why it would cause the traversal to immediately abort and exit though, but I'll downgrade it from an error to a warning since it's only an indication to the user that the traversal may have missed some files.
