### ISSUE TITLE
🐛 `rome check .` seems to run in an infinite loop with 99% CPU usage

### ISSUE THREAD

**Issue by RobinMalfait** [rome/tools#3330]
### Environment information

```bash
OS Information:
- macOS Monterey, version 12.5.1 (21G83)
- Apple M1 Max

Context:
- Wanted to play with the new version in Tailwind CSS to see how it behaves when running `rome format . --write` or `rome check .`

Installation:
- `npm install rome@next --save-dev`

Versions:
- Node: v18.8.0
- NPM: 8.18.0
```

### What happened?

Every now and then when you release a new version, I try to play with it on a real codebase, in my case I'm playing with things in the Tailwind CSS codebase (https://github.com/tailwindlabs/tailwindcss).

I basically installed rome:
```sh
npm install rome@next --save-dev
```

... once that was done, I executed:
```sh
rome check .
```

It shows a bunch of output already, but then just hangs, and it looks like this: 
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/1834413/193917928-926a0b92-527a-4687-a9ef-a2d7bb88714c.png">

When I looked at activity monitor I saw this:
![image](https://user-images.githubusercontent.com/1834413/193918011-17f9be03-f656-4225-b247-60397d9fed38.png)

I eventually had to quit rome by using `ctrl+c` and luckily that worked without me force killing the process.

### Expected result

I would have expected that the command (`rome check .`) did its job and once it was done, that it exited the process successfully.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by RobinMalfait** [comment]
Aha! Yep it's stuck on a 3.4 MB `.js` file. It's 116 281 lines of code long file. It's also a generated files so might be useful to ignore that one specific file. 

Could be nice if Rome warned about large files and ignore them or ask you if it should be handled or not. Not sure, just thinking about improving the UX.

**Comment by leops** [comment]
We already have a file size threshold to avoid printing the diff to the console if it's over 1 MiB, so the fix for this could simply be to move this check earlier in the pipeline, probably before we even start parsing (and it would also benefit the Language Server to avoid hogging CPU and memory when a user opens a minified bundle in their editor). It may need some sort of escape hatch though, like an `--ignore-size-limit` flag on the CLI for users that really do want to reformat a minified bundle ...
