### ISSUE TITLE
🐛 Internal Rome error formatting

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3391]
### Environment information

```bash
main
```

### What happened?

1. Rome crashed because of an internal error 

![image](https://user-images.githubusercontent.com/1203881/195024075-5a686be6-d6f0-4010-a77a-fa25cffbb2e2.png)

The internal errors lack the otherwise used separator line which makes it difficult to see the start/end of the error messages.

### Expected result

* Internal errors to be clearly separated from other errors, similar to how "normal" diagnostics are separated by a line.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by leops** [comment]
I don't think internal errors are explicitly missing the separator (unless there's an additional bug I don't know about), but the separator is printed to fill the width up to 100 columns so it won't be displayed if the header line is longer. One easy "fix" would be to clamp the length of the line to be at least 10 or 15, to force the separator be displayed even when the header text is long

**Comment by MichaReiser** [comment]
I would expect that *Rome encountered an unexpected error* which shouldn't leave enough space for the separator as it isn't exceeding the 100 column width?

**Comment by leops** [comment]
> I would expect that _Rome encountered an unexpected error_ which shouldn't leave enough space for the separator as it isn't exceeding the 100 column width?

That line is printed by the panic hook of the CLI and not by the diagnostics printer, since the panic hooks doesn't know if the panic will be caught by a `catch_unwind` its message is printed unconditionally, even if the panic is later printed as a diagnostic on the console thread after being caught.
As part of the diagnostics refactor I envisioned the `rome_diagnostics` crate would expose specialized versions of `panic!`, `catch_unwind` and a panic hook implementation to support panicking with a diagnostic, as part of this it would be possible to suppress the output of the panic hook if a `catch_unwind` is known to be active (through a thread-local flag)
