### ISSUE TITLE
🐛 `rome stop`: Connection unexpectedly closed

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3414]
### Environment information

main (3a6e4346ee26a5a5d2f777ce62995cb900e0ce66)

### What happened?

```bash
❯ cargo run --bin rome -- start 
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rome start`
The Rome server was already running

rome on  fix/unknown-filtered-rule [$?] via 🦀 v1.64.0 
❯ cargo run --bin rome -- stop
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/rome stop`
remote connection write task exited with an error

Caused by:
    the connection to the remote workspace was unexpectedly closed
The Rome server was successfully stopped
```

### Expected result

`stop` to not print any error messages. 

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by MichaReiser** [comment]
CC: @leops

**Comment by leops** [comment]
Ah yes that's an unfortunate issue with how the stop command and remote connection error reporting interact. Because the asynchronous tasks managing the remote connection are run in the background they don't really have a way to "return" an error to the main thread, so any error they encounter is directly printed to stderr. On the server side the stop command is implemented as a very simple broadcast that causes all connections to terminate immediately, including the connection to the client that initially sent the shutdown request. This means that even though the server was stopped successfully (as noted by the final line of the CLI output), the remote connection tasks still get abruptly cut off and print an error message to the console.
I think the easiest fix would be to have the remote write task detect that it's about to send a shutdown request, signal it to the read task to have it abort, send the request and finally shut itself down cleanly too.
