### ISSUE TITLE
Rule name in ignore comment and diagnostic differ

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3446]
## Example

```javascript
class Handler {
  private _next(
		subResult: TSubResult,
		taskIndex: number,
		valuesPerTask: number,
	) {
		for (const nextHandler of this.nextHandlers) {
			nextHandler.apply(undefined, arguments);
		}
	}
}
```

Shows a diagnostic that a rest parameter should be used instead of `arguments` with the name `correctness/noArguments`

![image](https://user-images.githubusercontent.com/1203881/196621101-f669e0f2-a6f2-4cea-937a-858d070dcf69.png)

However, the suppression comment requires to use the name `correctness/noArguments`:

```javascript
for (const nextHandler of this.nextHandlers) {
	// rome-ignore lint(correctness/noArguments): Too tired to fiddle with types
	nextHandler.apply(undefined, arguments);
}
```

I had to visit our website to look up the suppression comment format because I used the name shown in the diagnostic rather than `lint(correctness/noArguments)`. 

## Expected

That's up for discussion. Ideally, the names shown in diagnostic should match the names in the suppression comments.

**Comment by MichaReiser** [comment]
CC: @leops

**Comment by leops** [comment]
The reason for this is that the suppression comment parser is implemented in the analyzer and expects the name of a rule (written as `<group>/<rule>`), while the diagnostics show a static `Category` that's global to the entire toolchain so the category for diagnostics emitted by lint rule are prefixed with `lint/` before the rule name.
We could change the syntax of suppression comments to simply be `rome ignore <Category>: <reason>` instead of `rome_ignore <SuppressionCategory>(<value>): <reason>`, although we'd need to define a subset of categories that are allowed to be suppressed to prevent parser diagnostics or CLI errors to be suppressed

**Comment by MichaReiser** [comment]
Thank you @leops for the explanation. Do I understand correctly that your suggestion to allow `rome ignore <Category>: <reason>` would allow me to write `rome ignore lint/correctness/noArguments`? 

My understanding is that the `lint` prefix is common to all lint rules so that `rome_analyze` could continue to test if the category name starts with `lint` and ignore all others.
