### ISSUE TITLE
🐛 VSCode extension linting comments

### ISSUE THREAD

**Issue by dev-ardi** [rome/tools#3490]
### Environment information

```bash
Rome 0.10, Windows 10, Extension v0.16.1
```

### What happened?

![image](https://user-images.githubusercontent.com/47633543/197965484-0bf3c3c7-919e-497c-b728-8a5f7cbec2da.png)

### Expected result

It should ignore comments

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
@dev-ardi Are you able to reproduce it using our playground? If so, could you please share it here?
If not, could you please share sample? It might be an issue related to the VSCode extension then.

**Comment by leops** [comment]
Since the diagnostic doesn't seem to be positioned correctly and doesn't match the code contained in the comment (and the linter rules don't have a way to match on comments anyway), this makes me think it's actually an issue with the state of the document going out of sync between the editor and language server

**Comment by ematipico** [comment]
> @ematipico where is this playground?

https://play.rome.tools/

**Comment by MichaReiser** [comment]
@dev-ardi are you able to reproduce this issue with the latest preview release?

**Comment by dev-ardi** [comment]
Nope, seems to be completely fixed now 🤠
