### ISSUE TITLE
📎 Automatically reload `rome.json` changes

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3522]
## Goal

Automatically apply changes made to the `rome.json` in the VS Code. 

## Task

* Listen to changes to the `rome.json` file in the VS Code extension
* Send the update configuration command to the LSP on change.,

**Comment by MichaReiser** [comment]
I made changes to the `rome.json` file but the changes aren't picked up in the latest nightly version

**Comment by MichaReiser** [comment]
The "reload" works as expected but the user must close all files for the changes to take effect.

**Comment by leops** [comment]
I imagine that's because we don't push an update to the diagnostics of open documents after the configuration change happens, so the language server needs an incoming event from the editor (re-opening the document might work but theoretically simply editing the content of the file should be enough to trigger a linter pass with the new configuration)

**Comment by ematipico** [comment]
I wonder if other VSCode  extensions like eslint, prettier, deno, etc. suffer from the same "bug". I would exclude prettier because formatting happens via events and there aren't diagnostics. We should check eslint.
