### ISSUE TITLE
☂️  Fast releases

### ISSUE THREAD

**Issue by sebmck** [rome/tools#3661]
### Description

If we have bug fixes then we should be aiming to get a patch release out ASAP. This could mean a patch release a day. It's my understanding we aren't currently situated to handle this very well. Related #3660.

**Comment by ematipico** [comment]
@sebmck I am going to take over the issue making it an umbrella. This was my initial plan for automated releases inside our repository, which I proposed some month ago. It's not a simple easy task because the works needs to take in consideration many aspects:
- changelogs;
- documentation;
- nightly releases;
