### ISSUE TITLE
📎 Remove "preview" label from VSCode extension

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3701]
### Description

We should bump the VS Code extension to a version with `major != 0` to indicate its production readiness. This should remove the "Preview" flag from the VS Code marketplace page.

**Comment by ematipico** [comment]
I think we can remove the "preview" - it's just a field in the `package.json` - but I don't think a `1.0.0` version reflects the current status of the extension, mostly because of all the [known limitations](https://github.com/rome/tools/blob/main/editors/vscode/README.md#known-limitations) we have.

**Comment by MichaReiser** [comment]
Ahh, that's it. If that does the job.
