### ISSUE TITLE
📎 Introduce `performance` group and move `noDelete` to new group

### ISSUE THREAD

**Issue by MichaReiser** [rome/tools#3719]
## Motivation

The `noDelete` rule isn't about correctness but performance. Using the `delete` operator in performance sensitive code can result in significantly slower runtime because JIT may de-opt some code (or have to re-JIT code). 

That's why the `noDelete` rule should be moved to the performance group.

See [this discussion](https://github.com/rome/tools/discussions/3614#discussioncomment-4123962) on more details on why to move the rule.

## Task

* Introduce new performance group
* Move `noDelete` rule to new group
* Improve the wording of the `noDelete` diagnostic to clearly explain the motivation

**Comment by MichaReiser** [comment]
There may be some cases where the use of `delete` has undesired effects [resource](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete)

Which may be reason to leave it in the correctness group but we should improve the explanation of the rule

**Comment by DhrjArun** [comment]
assign this issue to me.

**Comment by MichaReiser** [comment]
> assign this issue to me.

I should have removed the good first issue label when I noticed that there are some correctness problems too. Part of this issue is to reason about whether the rule should be moved into the performance group and how to best explain the correctness issues that may come with the use of `delete`.

**Comment by DhrjArun** [comment]
Thanks @MichaReiser I will read discussion and let you know.

**Comment by DhrjArun** [comment]
`delete` operator can be used incorrectly in the case of
1. deleting a variable 
```js
var x = "a"
let y = "b"
const z = "c"

delete x // SyntaxError in strict mode otherwise returns false
delete y // SyntaxError in strict mode
delete z // SyntaxError in strict mode
```
2. deleting a non-configurable member of object
```js
const app = {}
Object.defineProperty(app, "name", { value: "rome", configurable: false })

delete app.name // TypeError in strict mode otherwise returns false
```
3. deleting the built in object or its member like Math, Array, will lead to Reference Error in the code.
```js
delete window.Math
```

Rome parser throws `the target for a delete operator cannot be a single identifier` for 1st case -- `delete x` [(Playground)](https://docs.rome.tools/playground/?indentStyle=space&trailingComma=none&code=dgBhAHIAIAB4ACAAPQAgACIAYQAiAAoAbABlAHQAIAB5ACAAPQAgACIAYgAiAAoAYwBvAG4AcwB0ACAAegAgAD0AIAAiAGMAIgAKAAoAZABlAGwAZQB0AGUAIAB4ADsACgBkAGUAbABlAHQAZQAgAHkAOwAKAGQAZQBsAGUAdABlACAAegA7AA%3D%3D&typescript=false&jsx=false). Just like this, We can implement the logic in rome_js_parser for checking the 2nd case and throw error if it's in strict mode or warning Otherwise. 

So I think we can have a rule `lint/correctness/noDeleteNative` for for case 3.

Another rule `lint/performance/noDelete` we can have  for performance issue. And we can make this rule recommendation to false. This rule will provide `undefined` alternative code-action for these.
```js
const obj = { name: ""}
const list = [1, 2, 3, 4]

delete obj.name // valid
delete list[1] // valid
```

@MichaReiser let me know what do you think
