### ISSUE TITLE
📎 Lint cases similar to `no-dupe-keys`

### ISSUE THREAD

**Issue by jeysal** [rome/tools#3731]
### Description

https://github.com/rome/tools/pull/3562 provided the initial implementation of `no-dupe-keys` for https://github.com/rome/tools/issues/3364
However, ESLint's `no-dupe-keys` covers cases that the initial implementation does not cover yet.
Namely, keys that are differently formatted numbers (e.g. `1` vs `0x1`).
These cases are documented in the test: https://github.com/rome/tools/blob/8c38054dbb090476742bebaec8e501e29dccc4d3/crates/rome_js_analyze/tests/specs/nursery/noDupeKeys.js#L17-L29

We can additionally think about whether we want to fail lint on `a` vs `['a']` too. However, my stance on this is that stopping short of computed property names is a good place to draw the line. Analyzing computed properties and linting `a` vs `['a']` specifically because there is a single literal in the computed property, but not linting `a` vs `['' + 'a']` or vs `[a /* const a = 'a' */]` because it's there seems like a much weirder place to draw the line :sweat_smile: 
I think we should not do it just because ESLint does it. Instead, I think we should have another rule that autofixes `['a']` to `a`.
@xunilrj @ematipico do you agree? (always a gamble if I figured out the right people to tag :P)

**Comment by jeysal** [comment]
Can someone label and if necessary add to https://github.com/rome/tools/issues/3358 or another appropriate umbrella please :)

**Comment by ematipico** [comment]
@jeysal

> Can someone label and if necessary add to https://github.com/rome/tools/issues/3358 or another appropriate umbrella please :)

That's done

>  @xunilrj @ematipico do you agree? (always a gamble if I figured out the right people to tag :P)

You can use `.github/CODEOWNERS` as reference. You tagged the correct people :) 

Overall, I agree with your idea to where we should draw the line. Actually, now that I think about it, why don't split the rule in three? As far I can see, there are some niche cases that ... yes, they eventually do the same, but their use cases can differ.

For example, cases where we check for number literals or computed properties. The check of number literals seems to me a niche case (personally , I never encountered such cases) for libraries that work with  graphs, animations or rendering engines, and we could **not recommend** and people opt-in only if they want.

For computed properties, it's mostly for us to help our mental sanity, because the logic can be quite messy and complex.

**Comment by ematipico** [comment]
> @ematipico three rules would make sense to me. I think they should be something like
> 
>     1. `no-dupe-keys` (as currently implemented)
> 
>     2. `simple-number-keys` (autofix e.g. `0x1` to `1`, safe)
> 
>     3. `no-literal-computed-keys` (autofix e.g. `["a"]` to `a`, safe)
> 
> 
> Is this what you envisioned too?

That's it! I am going to update the umbrella issue :)

**Comment by ematipico** [comment]
Closing in favour of #3739 , where the new rules are tracked there
