### ISSUE TITLE
`noUnsafeOptionalChain`,  no-unsafe-optional-chaining

### ISSUE THREAD

**Issue by ematipico** [rome/tools#3985]
https://eslint.org/docs/latest/rules/no-unsafe-optional-chaining

**Comment by denbezrukov** [comment]
@ematipico I think so. 
But I don't think that it's a problem. Because `useOptionalChain` converts optional chain like expressions.
For example `foo && foo.bar` or `(foo || {}).bar`.  We can replace both expressions with `foo?.bar`. 
If I understand `noUnsafeOptionalChain` correctly it checks only optional chains. But problems which are described in descriptions can also be with optional _**like**_ chains.  
Example from docs:
```
1 in obj?.foo;  // TypeError
with (obj?.foo);  // TypeError
for (bar of obj?.foo);  // TypeError
bar instanceof obj?.foo;  // TypeError
const { bar } = obj?.foo;  // TypeError
```

But we have the same problems with these expressions.
```
1 in obj && obj.foo;    // TypeError
1 in (obj || {}).foo;    // TypeError

with (obj && obj.foo);  // TypeError
with ((obj || {}).foo);  // TypeError

for (bar of (obj && obj.foo);  // TypeError
for (bar of (obj || {}).foo);  // TypeError

bar instanceof (obj || {}).foo;  // TypeError
bar instanceof obj && obj.foo;  // TypeError

const { bar } = obj && obj.foo;  // TypeError
const { bar } = (obj || {}).foo;  // TypeError
```

**Comment by denbezrukov** [comment]
Can I take it?

**Comment by ematipico** [comment]
I'm not really sure to be honest. It seems to me that the option is meant to cover some edge case... 

My suggestion is to skip it for now
