### ISSUE TITLE
📎 Considering removing `hr` from console output

### ISSUE THREAD

**Issue by sebmck** [rome/tools#981]
Right now we render this huge dashed lines to separate some content. I think we use whitespace and indentation efficiently enough to distinguish between different sections. I have been staring at the output for way too long so curious if others have the same thoughts.

**Comment by sebmck** [comment]
Wanted to ping this issue and see if anyone else had thoughts on this and think it would be a positive improvement.

**Comment by ematipico** [comment]
Personally, I found the `hr` refreshing, maybe because it was the first time I had seen it used by CLI in an efficient way.

From another point of view, I found it superfluous when copying it somewhere else because it might longer than the code blocked used inside a chat bloc or an issue block.

Maybe we could try to remove it and see how's the look and feel. I don't have strong opinions.

**Comment by sebmck** [comment]
Yeah that's how I feel too. It's not common for CLI tools to adapt to terminal width and I guess having it makes it a lot more obvious. We can maybe do some tweaks since some people have missed that the filename is included to the left, but not sure if that's common.

**Comment by sebmck** [comment]
For that case it's because VSCode doesn't set `columns` so we're defaulting to like 180 columns and causes the wrapping.

**Comment by jamiebuilds** [comment]
Hi! Thank you for opening this issue

We recently made the decision to [migrate the Rome codebase to Rust](https://rome.tools/blog/2021/09/21/rome-will-be-rewritten-in-rust) and making some significant changes to its architecture. We've also decided not to release the previous version written in TypeScript.

We're going through and closing pull requests and issues that were specific to the TypeScript codebase, including this one. Thank you for taking the time to open it.

Thanks again!
